### ISSUE TITLE
Result Count

### ISSUE THREAD

**Issue by Shreyas-Ashtamkar** [Workhub-Shreyas/All-Search#16]
- [x] ![Screenshot_2021-11-28-16-30-09-42_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/51398602/143765078-22695721-94bb-484e-b5fd-a047a88ab0fe.jpg)

Result count to be shown.

**Comment by Workhub-Shreyas** [comment]
Current Implementation including empty, that should not happen.
